// <auto-generated />
namespace IITAcademicAutomationSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Marging_Ishmam_Task : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Marging_Ishmam_Task));
        
        string IMigrationMetadata.Id
        {
            get { return "201610281552073_Marging_Ishmam_Task"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
